FROM centos:centos7

RUN yum update -y && yum clean all

RUN yum install -y epel-release
RUN yum update -y
RUN yum install -y \
	rpm-build gcc autoconf automake libtool make \
	httpd-devel curl-devel pcre2-devel check-devel jansson-devel hiredis-devel openssl-devel \
	httpd mod_ssl valgrind
	
ENV CJOSE_VERSION 0.6.2
ENV CJOSE_TGZ cjose-${CJOSE_VERSION}.tar.gz
RUN curl -L -o ${CJOSE_TGZ} https://github.com/zmartzone/cjose/releases/download/v${CJOSE_VERSION}/${CJOSE_TGZ}
RUN tar zxvf ${CJOSE_TGZ}
RUN cd cjose-${CJOSE_VERSION} && \
	./configure CFLAGS="-g" && \
	make && \
	make test && \
	make install	

COPY . mod_auth_openidc

ENV PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:/usr/local/lib/pkgconfig
RUN cd mod_auth_openidc && \
	./autogen.sh && \
	./configure CFLAGS="-g" && \
	make clean && \
	make
RUN cd mod_auth_openidc && \
	export LD_LIBRARY_PATH="/usr/lib" && \
	make check || (cat test-suite.log && exit -1)
RUN cd mod_auth_openidc && \
	make install 

RUN openssl req -new -days 365 -x509 -nodes -out /etc/pki/tls/certs/localhost.crt -keyout /etc/pki/tls/private/localhost.key -subj "/C=NL/CN=localhost"
RUN echo "LoadModule auth_openidc_module modules/mod_auth_openidc.so" > /etc/httpd/conf.modules.d/00-openidc.conf
RUN mkdir -p /etc/apache2/conf-available && touch /etc/apache2/conf-available/openidc.conf 
RUN ln -s /etc/apache2/conf-available/openidc.conf /etc/httpd/conf.d/openidc.conf
RUN sed -i '/^LogLevel/s/ *$/ & auth_openidc\:trace1/g' /etc/httpd/conf.d/ssl.conf
RUN mkdir -p /etc/apache2 && touch /etc/apache2/envvars && chmod a+x /etc/apache2/envvars
RUN ln -s /usr/sbin/httpd /usr/sbin/apache2 

RUN /usr/sbin/httpd -M

# lost in curl_global_init
#RUN echo "definitely lost: 5,432 bytes in 37 blocks" > /tmp/valgrind.result
# local
#RUN echo "definitely lost: 10,256 bytes in 68 blocks" > /tmp/valgrind.result
# github
RUN echo "definitely lost: 28,880 bytes in 192 blocks" > /tmp/valgrind.result
