FROM binhex/arch-base

RUN pacman --noconfirm -S \
	gcc openssl curl apache jansson pkg-config hiredis automake autoconf make check valgrind

RUN sed  -i '1i Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch' /etc/pacman.d/mirrorlist
RUN echo "[core-debug]" >> /etc/pacman.conf && echo "Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
RUN pacman --noconfirm -Sy glibc glibc-debug

ENV CJOSE_VERSION 0.6.2
ENV CJOSE_TGZ cjose-${CJOSE_VERSION}.tar.gz
RUN curl -L -o ${CJOSE_TGZ} https://github.com/zmartzone/cjose/releases/download/v${CJOSE_VERSION}/${CJOSE_TGZ}
RUN tar zxvf ${CJOSE_TGZ}
RUN cd cjose-${CJOSE_VERSION} && \
	./configure && \
	make && \
	make test && \
	make install

COPY . mod_auth_openidc
ENV PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:/usr/local/lib/pkgconfig
RUN cd mod_auth_openidc && \
	./autogen.sh && \
	./configure && \
	make clean && \
	make
RUN cd mod_auth_openidc && \
	make check || (cat test-suite.log && exit -1)
RUN cd mod_auth_openidc && \
	make install 

RUN mkdir -p /etc/apache2/conf-available && touch /etc/apache2/conf-available/openidc.conf
RUN echo "LoadModule auth_openidc_module modules/mod_auth_openidc.so" >> /etc/httpd/conf/httpd.conf
RUN echo "Include /etc/apache2/conf-available/openidc.conf" >> /etc/httpd/conf/httpd.conf
RUN sed -i '/^LogLevel/s/ *$/ & auth_openidc\:trace1/g' /etc/httpd/conf/httpd.conf
RUN echo "LoadModule proxy_module modules/mod_proxy.so" >> /etc/httpd/conf/httpd.conf
RUN echo "LoadModule proxy_http_module modules/mod_proxy_http.so" >> /etc/httpd/conf/httpd.conf
RUN echo "LoadModule ssl_module modules/mod_ssl.so" >> /etc/httpd/conf/httpd.conf
RUN echo "Include conf/extra/httpd-ssl.conf" >> /etc/httpd/conf/httpd.conf
RUN echo "LoadModule socache_shmcb_module modules/mod_socache_shmcb.so" >> /etc/httpd/conf/httpd.conf
#RUN echo "Mutex sem" >> /etc/httpd/conf/httpd.conf

RUN openssl req -new -days 365 -x509 -nodes -out /etc/httpd/conf/server.crt -keyout /etc/httpd/conf/server.key -subj "/CN=apache"

RUN mkdir -p /etc/apache2 && touch /etc/apache2/envvars && chmod a+x /etc/apache2/envvars
RUN ln -s /usr/sbin/httpd /usr/sbin/apache2 

RUN /usr/sbin/httpd  -M
